# Brute-force hack a Union Route Cipher.

# Designed for whole-word transposition ciphers with variable rows & columns.
# Assumes encryption began at either top or bottom of a column.
# Possible keys auto-generated based on number of columns & rows input.
# Key indicates the order to read columns and the direction to traverse.
# Negative column numbers mean start at bottom and read up.
# Positive column numbers means start at top & read down.

# Example below is for 4x4 matrix with key -1 2 -3 4.
# Note "0" is not allowed.
# Arrows show encryption route; for negative key values read UP.

#   1   2   3   4
#  ___ ___ ___ ___
# | ^ | | | ^ | | | MESSAGE IS WRITTEN
# |_|_|_v_|_|_|_v_|
# | ^ | | | ^ | | | ACROSS EACH ROW
# |_|_|_v_|_|_|_v_|
# | ^ | | | ^ | | | IN THIS MANNER
# |_|_|_v_|_|_|_v_|
# | ^ | | | ^ | | | LAST ROW IS FILLED WITH DUMMY WORDS
# |_|_|_v_|_|_|_v_|
# START        END

# Required inputs - a text message, # of columns, # of rows, key string
# Requires custom-made "perms" module to generate keys
# Prints off key used and translated plaintext


require_relative "perms" # Perms.perms()

#==============================================================================
# USER INPUT:

# the string to be decrypted (type or paste between triple-quotes):
CIPHERTEXT = "REST TRANSPORT YOU GODWIN VILLAGE ROANOKE WITH ARE YOUR IS JUST SUPPLIES FREE SNOW HEADING TO GONE TO SOUTH FILLER"

# the number of columns believed to be in the transposition matrix:
COLS = 4

# the number of rows believed to be in the transposition matrix:
ROWS = 5
#==============================================================================

# Turn ciphertext into list, call validation & decryption functions.
def main
  cipherlist = CIPHERTEXT.strip.split(/\s/)
  validate_col_row(cipherlist)
  decrypt(cipherlist)
end

# Check that input columns & rows are valid vs. message length.
def validate_col_row(cipherlist)
  factors = []
  len_cipher = cipherlist.length
  for i in (2...len_cipher)
    factors.append(i) if len_cipher % i == 0
  end
  puts
  puts "Length of cipher = #{len_cipher}"
  puts "Acceptable column/row values include: #{factors}"
  puts

  if ROWS * COLS != len_cipher
    puts "Error - Input columns & rows not factors of length of cipher. Terminating program."
    exit(1)
  end
end

# Turn columns into items in list of lists & decrypt ciphertext.
def decrypt(cipherlist)
  col_combos = Perms.perms(COLS)
  for key in col_combos
    translation_matrix = Array.new(COLS)
    plaintext = ""
    start = 0
    stop = ROWS
    for k in key
      if k.negative? # reading bottom-to-top of column
        col_items = cipherlist[start...stop]
      elsif k.positive? # reading top-to-bottom of columnn
        col_items = cipherlist[start...stop].reverse
      end
      translation_matrix[k.abs - 1] = col_items
      start += ROWS
      stop  += ROWS
    end # k

    # loop through nested lists popping off last item to a new list:
    for i in (0...ROWS)
      for matrix_col in translation_matrix
        plaintext += "#{matrix_col.pop} "
      end
    end # i
    puts
    puts "using key = #{key}"
    puts "translated = #{plaintext}"
  end # key
  puts
  puts "number of keys = #{col_combos.length}"
end

main()

# 🤖 ch04 $ ruby route_cipher_hacker.rb

# Length of cipher = 20
# Acceptable column/row values include: [2, 4, 5, 10]


# using key = [-1, -2, -3, -4]
# translated = VILLAGE IS HEADING FILLER GODWIN YOUR SNOW SOUTH YOU ARE FREE TO TRANSPORT WITH SUPPLIES GONE REST ROANOKE JUST TO

# using key = [-1, -2, -3, 4]
# translated = VILLAGE IS HEADING TO GODWIN YOUR SNOW GONE YOU ARE FREE TO TRANSPORT WITH SUPPLIES SOUTH REST ROANOKE JUST FILLER

# using key = [-1, -2, 3, -4]
# translated = VILLAGE IS JUST FILLER GODWIN YOUR SUPPLIES SOUTH YOU ARE FREE TO TRANSPORT WITH SNOW GONE REST ROANOKE HEADING TO

# using key = [-1, -2, 3, 4]
# translated = VILLAGE IS JUST TO GODWIN YOUR SUPPLIES GONE YOU ARE FREE TO TRANSPORT WITH SNOW SOUTH REST ROANOKE HEADING FILLER

# using key = [-1, 2, -3, -4]
# translated = VILLAGE ROANOKE HEADING FILLER GODWIN WITH SNOW SOUTH YOU ARE FREE TO TRANSPORT YOUR SUPPLIES GONE REST IS JUST TO

# using key = [-1, 2, -3, 4]
# translated = VILLAGE ROANOKE HEADING TO GODWIN WITH SNOW GONE YOU ARE FREE TO TRANSPORT YOUR SUPPLIES SOUTH REST IS JUST FILLER

# using key = [-1, 2, 3, -4]
# translated = VILLAGE ROANOKE JUST FILLER GODWIN WITH SUPPLIES SOUTH YOU ARE FREE TO TRANSPORT YOUR SNOW GONE REST IS HEADING TO

# using key = [-1, 2, 3, 4]
# translated = VILLAGE ROANOKE JUST TO GODWIN WITH SUPPLIES GONE YOU ARE FREE TO TRANSPORT YOUR SNOW SOUTH REST IS HEADING FILLER

# using key = [1, -2, -3, -4]
# translated = REST IS HEADING FILLER TRANSPORT YOUR SNOW SOUTH YOU ARE FREE TO GODWIN WITH SUPPLIES GONE VILLAGE ROANOKE JUST TO

# using key = [1, -2, -3, 4]
# translated = REST IS HEADING TO TRANSPORT YOUR SNOW GONE YOU ARE FREE TO GODWIN WITH SUPPLIES SOUTH VILLAGE ROANOKE JUST FILLER

# using key = [1, -2, 3, -4]
# translated = REST IS JUST FILLER TRANSPORT YOUR SUPPLIES SOUTH YOU ARE FREE TO GODWIN WITH SNOW GONE VILLAGE ROANOKE HEADING TO

# using key = [1, -2, 3, 4]
# translated = REST IS JUST TO TRANSPORT YOUR SUPPLIES GONE YOU ARE FREE TO GODWIN WITH SNOW SOUTH VILLAGE ROANOKE HEADING FILLER

# using key = [1, 2, -3, -4]
# translated = REST ROANOKE HEADING FILLER TRANSPORT WITH SNOW SOUTH YOU ARE FREE TO GODWIN YOUR SUPPLIES GONE VILLAGE IS JUST TO

# using key = [1, 2, -3, 4]
# translated = REST ROANOKE HEADING TO TRANSPORT WITH SNOW GONE YOU ARE FREE TO GODWIN YOUR SUPPLIES SOUTH VILLAGE IS JUST FILLER

# using key = [1, 2, 3, -4]
# translated = REST ROANOKE JUST FILLER TRANSPORT WITH SUPPLIES SOUTH YOU ARE FREE TO GODWIN YOUR SNOW GONE VILLAGE IS HEADING TO

# using key = [1, 2, 3, 4]
# translated = REST ROANOKE JUST TO TRANSPORT WITH SUPPLIES GONE YOU ARE FREE TO GODWIN YOUR SNOW SOUTH VILLAGE IS HEADING FILLER

# using key = [-1, -2, -4, -3]
# translated = VILLAGE IS FILLER HEADING GODWIN YOUR SOUTH SNOW YOU ARE TO FREE TRANSPORT WITH GONE SUPPLIES REST ROANOKE TO JUST

# using key = [-1, -2, -4, 3]
# translated = VILLAGE IS TO HEADING GODWIN YOUR GONE SNOW YOU ARE TO FREE TRANSPORT WITH SOUTH SUPPLIES REST ROANOKE FILLER JUST

# using key = [-1, -2, 4, -3]
# translated = VILLAGE IS FILLER JUST GODWIN YOUR SOUTH SUPPLIES YOU ARE TO FREE TRANSPORT WITH GONE SNOW REST ROANOKE TO HEADING

# using key = [-1, -2, 4, 3]
# translated = VILLAGE IS TO JUST GODWIN YOUR GONE SUPPLIES YOU ARE TO FREE TRANSPORT WITH SOUTH SNOW REST ROANOKE FILLER HEADING

# using key = [-1, 2, -4, -3]
# translated = VILLAGE ROANOKE FILLER HEADING GODWIN WITH SOUTH SNOW YOU ARE TO FREE TRANSPORT YOUR GONE SUPPLIES REST IS TO JUST

# using key = [-1, 2, -4, 3]
# translated = VILLAGE ROANOKE TO HEADING GODWIN WITH GONE SNOW YOU ARE TO FREE TRANSPORT YOUR SOUTH SUPPLIES REST IS FILLER JUST

# using key = [-1, 2, 4, -3]
# translated = VILLAGE ROANOKE FILLER JUST GODWIN WITH SOUTH SUPPLIES YOU ARE TO FREE TRANSPORT YOUR GONE SNOW REST IS TO HEADING

# using key = [-1, 2, 4, 3]
# translated = VILLAGE ROANOKE TO JUST GODWIN WITH GONE SUPPLIES YOU ARE TO FREE TRANSPORT YOUR SOUTH SNOW REST IS FILLER HEADING

# using key = [1, -2, -4, -3]
# translated = REST IS FILLER HEADING TRANSPORT YOUR SOUTH SNOW YOU ARE TO FREE GODWIN WITH GONE SUPPLIES VILLAGE ROANOKE TO JUST

# using key = [1, -2, -4, 3]
# translated = REST IS TO HEADING TRANSPORT YOUR GONE SNOW YOU ARE TO FREE GODWIN WITH SOUTH SUPPLIES VILLAGE ROANOKE FILLER JUST

# using key = [1, -2, 4, -3]
# translated = REST IS FILLER JUST TRANSPORT YOUR SOUTH SUPPLIES YOU ARE TO FREE GODWIN WITH GONE SNOW VILLAGE ROANOKE TO HEADING

# using key = [1, -2, 4, 3]
# translated = REST IS TO JUST TRANSPORT YOUR GONE SUPPLIES YOU ARE TO FREE GODWIN WITH SOUTH SNOW VILLAGE ROANOKE FILLER HEADING

# using key = [1, 2, -4, -3]
# translated = REST ROANOKE FILLER HEADING TRANSPORT WITH SOUTH SNOW YOU ARE TO FREE GODWIN YOUR GONE SUPPLIES VILLAGE IS TO JUST

# using key = [1, 2, -4, 3]
# translated = REST ROANOKE TO HEADING TRANSPORT WITH GONE SNOW YOU ARE TO FREE GODWIN YOUR SOUTH SUPPLIES VILLAGE IS FILLER JUST

# using key = [1, 2, 4, -3]
# translated = REST ROANOKE FILLER JUST TRANSPORT WITH SOUTH SUPPLIES YOU ARE TO FREE GODWIN YOUR GONE SNOW VILLAGE IS TO HEADING

# using key = [1, 2, 4, 3]
# translated = REST ROANOKE TO JUST TRANSPORT WITH GONE SUPPLIES YOU ARE TO FREE GODWIN YOUR SOUTH SNOW VILLAGE IS FILLER HEADING

# using key = [-1, -3, -2, -4]
# translated = VILLAGE HEADING IS FILLER GODWIN SNOW YOUR SOUTH YOU FREE ARE TO TRANSPORT SUPPLIES WITH GONE REST JUST ROANOKE TO

# using key = [-1, -3, -2, 4]
# translated = VILLAGE HEADING IS TO GODWIN SNOW YOUR GONE YOU FREE ARE TO TRANSPORT SUPPLIES WITH SOUTH REST JUST ROANOKE FILLER

# using key = [-1, -3, 2, -4]
# translated = VILLAGE JUST IS FILLER GODWIN SUPPLIES YOUR SOUTH YOU FREE ARE TO TRANSPORT SNOW WITH GONE REST HEADING ROANOKE TO

# using key = [-1, -3, 2, 4]
# translated = VILLAGE JUST IS TO GODWIN SUPPLIES YOUR GONE YOU FREE ARE TO TRANSPORT SNOW WITH SOUTH REST HEADING ROANOKE FILLER

# using key = [-1, 3, -2, -4]
# translated = VILLAGE HEADING ROANOKE FILLER GODWIN SNOW WITH SOUTH YOU FREE ARE TO TRANSPORT SUPPLIES YOUR GONE REST JUST IS TO

# using key = [-1, 3, -2, 4]
# translated = VILLAGE HEADING ROANOKE TO GODWIN SNOW WITH GONE YOU FREE ARE TO TRANSPORT SUPPLIES YOUR SOUTH REST JUST IS FILLER

# using key = [-1, 3, 2, -4]
# translated = VILLAGE JUST ROANOKE FILLER GODWIN SUPPLIES WITH SOUTH YOU FREE ARE TO TRANSPORT SNOW YOUR GONE REST HEADING IS TO

# using key = [-1, 3, 2, 4]
# translated = VILLAGE JUST ROANOKE TO GODWIN SUPPLIES WITH GONE YOU FREE ARE TO TRANSPORT SNOW YOUR SOUTH REST HEADING IS FILLER

# using key = [1, -3, -2, -4]
# translated = REST HEADING IS FILLER TRANSPORT SNOW YOUR SOUTH YOU FREE ARE TO GODWIN SUPPLIES WITH GONE VILLAGE JUST ROANOKE TO

# using key = [1, -3, -2, 4]
# translated = REST HEADING IS TO TRANSPORT SNOW YOUR GONE YOU FREE ARE TO GODWIN SUPPLIES WITH SOUTH VILLAGE JUST ROANOKE FILLER

# using key = [1, -3, 2, -4]
# translated = REST JUST IS FILLER TRANSPORT SUPPLIES YOUR SOUTH YOU FREE ARE TO GODWIN SNOW WITH GONE VILLAGE HEADING ROANOKE TO

# using key = [1, -3, 2, 4]
# translated = REST JUST IS TO TRANSPORT SUPPLIES YOUR GONE YOU FREE ARE TO GODWIN SNOW WITH SOUTH VILLAGE HEADING ROANOKE FILLER

# using key = [1, 3, -2, -4]
# translated = REST HEADING ROANOKE FILLER TRANSPORT SNOW WITH SOUTH YOU FREE ARE TO GODWIN SUPPLIES YOUR GONE VILLAGE JUST IS TO

# using key = [1, 3, -2, 4]
# translated = REST HEADING ROANOKE TO TRANSPORT SNOW WITH GONE YOU FREE ARE TO GODWIN SUPPLIES YOUR SOUTH VILLAGE JUST IS FILLER

# using key = [1, 3, 2, -4]
# translated = REST JUST ROANOKE FILLER TRANSPORT SUPPLIES WITH SOUTH YOU FREE ARE TO GODWIN SNOW YOUR GONE VILLAGE HEADING IS TO

# using key = [1, 3, 2, 4]
# translated = REST JUST ROANOKE TO TRANSPORT SUPPLIES WITH GONE YOU FREE ARE TO GODWIN SNOW YOUR SOUTH VILLAGE HEADING IS FILLER

# using key = [-1, -3, -4, -2]
# translated = VILLAGE FILLER IS HEADING GODWIN SOUTH YOUR SNOW YOU TO ARE FREE TRANSPORT GONE WITH SUPPLIES REST TO ROANOKE JUST

# using key = [-1, -3, -4, 2]
# translated = VILLAGE TO IS HEADING GODWIN GONE YOUR SNOW YOU TO ARE FREE TRANSPORT SOUTH WITH SUPPLIES REST FILLER ROANOKE JUST

# using key = [-1, -3, 4, -2]
# translated = VILLAGE FILLER IS JUST GODWIN SOUTH YOUR SUPPLIES YOU TO ARE FREE TRANSPORT GONE WITH SNOW REST TO ROANOKE HEADING

# using key = [-1, -3, 4, 2]
# translated = VILLAGE TO IS JUST GODWIN GONE YOUR SUPPLIES YOU TO ARE FREE TRANSPORT SOUTH WITH SNOW REST FILLER ROANOKE HEADING

# using key = [-1, 3, -4, -2]
# translated = VILLAGE FILLER ROANOKE HEADING GODWIN SOUTH WITH SNOW YOU TO ARE FREE TRANSPORT GONE YOUR SUPPLIES REST TO IS JUST

# using key = [-1, 3, -4, 2]
# translated = VILLAGE TO ROANOKE HEADING GODWIN GONE WITH SNOW YOU TO ARE FREE TRANSPORT SOUTH YOUR SUPPLIES REST FILLER IS JUST

# using key = [-1, 3, 4, -2]
# translated = VILLAGE FILLER ROANOKE JUST GODWIN SOUTH WITH SUPPLIES YOU TO ARE FREE TRANSPORT GONE YOUR SNOW REST TO IS HEADING

# using key = [-1, 3, 4, 2]
# translated = VILLAGE TO ROANOKE JUST GODWIN GONE WITH SUPPLIES YOU TO ARE FREE TRANSPORT SOUTH YOUR SNOW REST FILLER IS HEADING

# using key = [1, -3, -4, -2]
# translated = REST FILLER IS HEADING TRANSPORT SOUTH YOUR SNOW YOU TO ARE FREE GODWIN GONE WITH SUPPLIES VILLAGE TO ROANOKE JUST

# using key = [1, -3, -4, 2]
# translated = REST TO IS HEADING TRANSPORT GONE YOUR SNOW YOU TO ARE FREE GODWIN SOUTH WITH SUPPLIES VILLAGE FILLER ROANOKE JUST

# using key = [1, -3, 4, -2]
# translated = REST FILLER IS JUST TRANSPORT SOUTH YOUR SUPPLIES YOU TO ARE FREE GODWIN GONE WITH SNOW VILLAGE TO ROANOKE HEADING

# using key = [1, -3, 4, 2]
# translated = REST TO IS JUST TRANSPORT GONE YOUR SUPPLIES YOU TO ARE FREE GODWIN SOUTH WITH SNOW VILLAGE FILLER ROANOKE HEADING

# using key = [1, 3, -4, -2]
# translated = REST FILLER ROANOKE HEADING TRANSPORT SOUTH WITH SNOW YOU TO ARE FREE GODWIN GONE YOUR SUPPLIES VILLAGE TO IS JUST

# using key = [1, 3, -4, 2]
# translated = REST TO ROANOKE HEADING TRANSPORT GONE WITH SNOW YOU TO ARE FREE GODWIN SOUTH YOUR SUPPLIES VILLAGE FILLER IS JUST

# using key = [1, 3, 4, -2]
# translated = REST FILLER ROANOKE JUST TRANSPORT SOUTH WITH SUPPLIES YOU TO ARE FREE GODWIN GONE YOUR SNOW VILLAGE TO IS HEADING

# using key = [1, 3, 4, 2]
# translated = REST TO ROANOKE JUST TRANSPORT GONE WITH SUPPLIES YOU TO ARE FREE GODWIN SOUTH YOUR SNOW VILLAGE FILLER IS HEADING

# using key = [-1, -4, -2, -3]
# translated = VILLAGE HEADING FILLER IS GODWIN SNOW SOUTH YOUR YOU FREE TO ARE TRANSPORT SUPPLIES GONE WITH REST JUST TO ROANOKE

# using key = [-1, -4, -2, 3]
# translated = VILLAGE HEADING TO IS GODWIN SNOW GONE YOUR YOU FREE TO ARE TRANSPORT SUPPLIES SOUTH WITH REST JUST FILLER ROANOKE

# using key = [-1, -4, 2, -3]
# translated = VILLAGE JUST FILLER IS GODWIN SUPPLIES SOUTH YOUR YOU FREE TO ARE TRANSPORT SNOW GONE WITH REST HEADING TO ROANOKE

# using key = [-1, -4, 2, 3]
# translated = VILLAGE JUST TO IS GODWIN SUPPLIES GONE YOUR YOU FREE TO ARE TRANSPORT SNOW SOUTH WITH REST HEADING FILLER ROANOKE

# using key = [-1, 4, -2, -3]
# translated = VILLAGE HEADING FILLER ROANOKE GODWIN SNOW SOUTH WITH YOU FREE TO ARE TRANSPORT SUPPLIES GONE YOUR REST JUST TO IS

# using key = [-1, 4, -2, 3]
# translated = VILLAGE HEADING TO ROANOKE GODWIN SNOW GONE WITH YOU FREE TO ARE TRANSPORT SUPPLIES SOUTH YOUR REST JUST FILLER IS

# using key = [-1, 4, 2, -3]
# translated = VILLAGE JUST FILLER ROANOKE GODWIN SUPPLIES SOUTH WITH YOU FREE TO ARE TRANSPORT SNOW GONE YOUR REST HEADING TO IS

# using key = [-1, 4, 2, 3]
# translated = VILLAGE JUST TO ROANOKE GODWIN SUPPLIES GONE WITH YOU FREE TO ARE TRANSPORT SNOW SOUTH YOUR REST HEADING FILLER IS

# using key = [1, -4, -2, -3]
# translated = REST HEADING FILLER IS TRANSPORT SNOW SOUTH YOUR YOU FREE TO ARE GODWIN SUPPLIES GONE WITH VILLAGE JUST TO ROANOKE

# using key = [1, -4, -2, 3]
# translated = REST HEADING TO IS TRANSPORT SNOW GONE YOUR YOU FREE TO ARE GODWIN SUPPLIES SOUTH WITH VILLAGE JUST FILLER ROANOKE

# using key = [1, -4, 2, -3]
# translated = REST JUST FILLER IS TRANSPORT SUPPLIES SOUTH YOUR YOU FREE TO ARE GODWIN SNOW GONE WITH VILLAGE HEADING TO ROANOKE

# using key = [1, -4, 2, 3]
# translated = REST JUST TO IS TRANSPORT SUPPLIES GONE YOUR YOU FREE TO ARE GODWIN SNOW SOUTH WITH VILLAGE HEADING FILLER ROANOKE

# using key = [1, 4, -2, -3]
# translated = REST HEADING FILLER ROANOKE TRANSPORT SNOW SOUTH WITH YOU FREE TO ARE GODWIN SUPPLIES GONE YOUR VILLAGE JUST TO IS

# using key = [1, 4, -2, 3]
# translated = REST HEADING TO ROANOKE TRANSPORT SNOW GONE WITH YOU FREE TO ARE GODWIN SUPPLIES SOUTH YOUR VILLAGE JUST FILLER IS

# using key = [1, 4, 2, -3]
# translated = REST JUST FILLER ROANOKE TRANSPORT SUPPLIES SOUTH WITH YOU FREE TO ARE GODWIN SNOW GONE YOUR VILLAGE HEADING TO IS

# using key = [1, 4, 2, 3]
# translated = REST JUST TO ROANOKE TRANSPORT SUPPLIES GONE WITH YOU FREE TO ARE GODWIN SNOW SOUTH YOUR VILLAGE HEADING FILLER IS

# using key = [-1, -4, -3, -2]
# translated = VILLAGE FILLER HEADING IS GODWIN SOUTH SNOW YOUR YOU TO FREE ARE TRANSPORT GONE SUPPLIES WITH REST TO JUST ROANOKE

# using key = [-1, -4, -3, 2]
# translated = VILLAGE TO HEADING IS GODWIN GONE SNOW YOUR YOU TO FREE ARE TRANSPORT SOUTH SUPPLIES WITH REST FILLER JUST ROANOKE

# using key = [-1, -4, 3, -2]
# translated = VILLAGE FILLER JUST IS GODWIN SOUTH SUPPLIES YOUR YOU TO FREE ARE TRANSPORT GONE SNOW WITH REST TO HEADING ROANOKE

# using key = [-1, -4, 3, 2]
# translated = VILLAGE TO JUST IS GODWIN GONE SUPPLIES YOUR YOU TO FREE ARE TRANSPORT SOUTH SNOW WITH REST FILLER HEADING ROANOKE

# using key = [-1, 4, -3, -2]
# translated = VILLAGE FILLER HEADING ROANOKE GODWIN SOUTH SNOW WITH YOU TO FREE ARE TRANSPORT GONE SUPPLIES YOUR REST TO JUST IS

# using key = [-1, 4, -3, 2]
# translated = VILLAGE TO HEADING ROANOKE GODWIN GONE SNOW WITH YOU TO FREE ARE TRANSPORT SOUTH SUPPLIES YOUR REST FILLER JUST IS

# using key = [-1, 4, 3, -2]
# translated = VILLAGE FILLER JUST ROANOKE GODWIN SOUTH SUPPLIES WITH YOU TO FREE ARE TRANSPORT GONE SNOW YOUR REST TO HEADING IS

# using key = [-1, 4, 3, 2]
# translated = VILLAGE TO JUST ROANOKE GODWIN GONE SUPPLIES WITH YOU TO FREE ARE TRANSPORT SOUTH SNOW YOUR REST FILLER HEADING IS

# using key = [1, -4, -3, -2]
# translated = REST FILLER HEADING IS TRANSPORT SOUTH SNOW YOUR YOU TO FREE ARE GODWIN GONE SUPPLIES WITH VILLAGE TO JUST ROANOKE

# using key = [1, -4, -3, 2]
# translated = REST TO HEADING IS TRANSPORT GONE SNOW YOUR YOU TO FREE ARE GODWIN SOUTH SUPPLIES WITH VILLAGE FILLER JUST ROANOKE

# using key = [1, -4, 3, -2]
# translated = REST FILLER JUST IS TRANSPORT SOUTH SUPPLIES YOUR YOU TO FREE ARE GODWIN GONE SNOW WITH VILLAGE TO HEADING ROANOKE

# using key = [1, -4, 3, 2]
# translated = REST TO JUST IS TRANSPORT GONE SUPPLIES YOUR YOU TO FREE ARE GODWIN SOUTH SNOW WITH VILLAGE FILLER HEADING ROANOKE

# using key = [1, 4, -3, -2]
# translated = REST FILLER HEADING ROANOKE TRANSPORT SOUTH SNOW WITH YOU TO FREE ARE GODWIN GONE SUPPLIES YOUR VILLAGE TO JUST IS

# using key = [1, 4, -3, 2]
# translated = REST TO HEADING ROANOKE TRANSPORT GONE SNOW WITH YOU TO FREE ARE GODWIN SOUTH SUPPLIES YOUR VILLAGE FILLER JUST IS

# using key = [1, 4, 3, -2]
# translated = REST FILLER JUST ROANOKE TRANSPORT SOUTH SUPPLIES WITH YOU TO FREE ARE GODWIN GONE SNOW YOUR VILLAGE TO HEADING IS

# using key = [1, 4, 3, 2]
# translated = REST TO JUST ROANOKE TRANSPORT GONE SUPPLIES WITH YOU TO FREE ARE GODWIN SOUTH SNOW YOUR VILLAGE FILLER HEADING IS

# using key = [-2, -1, -3, -4]
# translated = IS VILLAGE HEADING FILLER YOUR GODWIN SNOW SOUTH ARE YOU FREE TO WITH TRANSPORT SUPPLIES GONE ROANOKE REST JUST TO

# using key = [-2, -1, -3, 4]
# translated = IS VILLAGE HEADING TO YOUR GODWIN SNOW GONE ARE YOU FREE TO WITH TRANSPORT SUPPLIES SOUTH ROANOKE REST JUST FILLER

# using key = [-2, -1, 3, -4]
# translated = IS VILLAGE JUST FILLER YOUR GODWIN SUPPLIES SOUTH ARE YOU FREE TO WITH TRANSPORT SNOW GONE ROANOKE REST HEADING TO

# using key = [-2, -1, 3, 4]
# translated = IS VILLAGE JUST TO YOUR GODWIN SUPPLIES GONE ARE YOU FREE TO WITH TRANSPORT SNOW SOUTH ROANOKE REST HEADING FILLER

# using key = [-2, 1, -3, -4]
# translated = ROANOKE VILLAGE HEADING FILLER WITH GODWIN SNOW SOUTH ARE YOU FREE TO YOUR TRANSPORT SUPPLIES GONE IS REST JUST TO

# using key = [-2, 1, -3, 4]
# translated = ROANOKE VILLAGE HEADING TO WITH GODWIN SNOW GONE ARE YOU FREE TO YOUR TRANSPORT SUPPLIES SOUTH IS REST JUST FILLER

# using key = [-2, 1, 3, -4]
# translated = ROANOKE VILLAGE JUST FILLER WITH GODWIN SUPPLIES SOUTH ARE YOU FREE TO YOUR TRANSPORT SNOW GONE IS REST HEADING TO

# using key = [-2, 1, 3, 4]
# translated = ROANOKE VILLAGE JUST TO WITH GODWIN SUPPLIES GONE ARE YOU FREE TO YOUR TRANSPORT SNOW SOUTH IS REST HEADING FILLER

# using key = [2, -1, -3, -4]
# translated = IS REST HEADING FILLER YOUR TRANSPORT SNOW SOUTH ARE YOU FREE TO WITH GODWIN SUPPLIES GONE ROANOKE VILLAGE JUST TO

# using key = [2, -1, -3, 4]
# translated = IS REST HEADING TO YOUR TRANSPORT SNOW GONE ARE YOU FREE TO WITH GODWIN SUPPLIES SOUTH ROANOKE VILLAGE JUST FILLER

# using key = [2, -1, 3, -4]
# translated = IS REST JUST FILLER YOUR TRANSPORT SUPPLIES SOUTH ARE YOU FREE TO WITH GODWIN SNOW GONE ROANOKE VILLAGE HEADING TO

# using key = [2, -1, 3, 4]
# translated = IS REST JUST TO YOUR TRANSPORT SUPPLIES GONE ARE YOU FREE TO WITH GODWIN SNOW SOUTH ROANOKE VILLAGE HEADING FILLER

# using key = [2, 1, -3, -4]
# translated = ROANOKE REST HEADING FILLER WITH TRANSPORT SNOW SOUTH ARE YOU FREE TO YOUR GODWIN SUPPLIES GONE IS VILLAGE JUST TO

# using key = [2, 1, -3, 4]
# translated = ROANOKE REST HEADING TO WITH TRANSPORT SNOW GONE ARE YOU FREE TO YOUR GODWIN SUPPLIES SOUTH IS VILLAGE JUST FILLER

# using key = [2, 1, 3, -4]
# translated = ROANOKE REST JUST FILLER WITH TRANSPORT SUPPLIES SOUTH ARE YOU FREE TO YOUR GODWIN SNOW GONE IS VILLAGE HEADING TO

# using key = [2, 1, 3, 4]
# translated = ROANOKE REST JUST TO WITH TRANSPORT SUPPLIES GONE ARE YOU FREE TO YOUR GODWIN SNOW SOUTH IS VILLAGE HEADING FILLER

# using key = [-2, -1, -4, -3]
# translated = IS VILLAGE FILLER HEADING YOUR GODWIN SOUTH SNOW ARE YOU TO FREE WITH TRANSPORT GONE SUPPLIES ROANOKE REST TO JUST

# using key = [-2, -1, -4, 3]
# translated = IS VILLAGE TO HEADING YOUR GODWIN GONE SNOW ARE YOU TO FREE WITH TRANSPORT SOUTH SUPPLIES ROANOKE REST FILLER JUST

# using key = [-2, -1, 4, -3]
# translated = IS VILLAGE FILLER JUST YOUR GODWIN SOUTH SUPPLIES ARE YOU TO FREE WITH TRANSPORT GONE SNOW ROANOKE REST TO HEADING

# using key = [-2, -1, 4, 3]
# translated = IS VILLAGE TO JUST YOUR GODWIN GONE SUPPLIES ARE YOU TO FREE WITH TRANSPORT SOUTH SNOW ROANOKE REST FILLER HEADING

# using key = [-2, 1, -4, -3]
# translated = ROANOKE VILLAGE FILLER HEADING WITH GODWIN SOUTH SNOW ARE YOU TO FREE YOUR TRANSPORT GONE SUPPLIES IS REST TO JUST

# using key = [-2, 1, -4, 3]
# translated = ROANOKE VILLAGE TO HEADING WITH GODWIN GONE SNOW ARE YOU TO FREE YOUR TRANSPORT SOUTH SUPPLIES IS REST FILLER JUST

# using key = [-2, 1, 4, -3]
# translated = ROANOKE VILLAGE FILLER JUST WITH GODWIN SOUTH SUPPLIES ARE YOU TO FREE YOUR TRANSPORT GONE SNOW IS REST TO HEADING

# using key = [-2, 1, 4, 3]
# translated = ROANOKE VILLAGE TO JUST WITH GODWIN GONE SUPPLIES ARE YOU TO FREE YOUR TRANSPORT SOUTH SNOW IS REST FILLER HEADING

# using key = [2, -1, -4, -3]
# translated = IS REST FILLER HEADING YOUR TRANSPORT SOUTH SNOW ARE YOU TO FREE WITH GODWIN GONE SUPPLIES ROANOKE VILLAGE TO JUST

# using key = [2, -1, -4, 3]
# translated = IS REST TO HEADING YOUR TRANSPORT GONE SNOW ARE YOU TO FREE WITH GODWIN SOUTH SUPPLIES ROANOKE VILLAGE FILLER JUST

# using key = [2, -1, 4, -3]
# translated = IS REST FILLER JUST YOUR TRANSPORT SOUTH SUPPLIES ARE YOU TO FREE WITH GODWIN GONE SNOW ROANOKE VILLAGE TO HEADING

# using key = [2, -1, 4, 3]
# translated = IS REST TO JUST YOUR TRANSPORT GONE SUPPLIES ARE YOU TO FREE WITH GODWIN SOUTH SNOW ROANOKE VILLAGE FILLER HEADING

# using key = [2, 1, -4, -3]
# translated = ROANOKE REST FILLER HEADING WITH TRANSPORT SOUTH SNOW ARE YOU TO FREE YOUR GODWIN GONE SUPPLIES IS VILLAGE TO JUST

# using key = [2, 1, -4, 3]
# translated = ROANOKE REST TO HEADING WITH TRANSPORT GONE SNOW ARE YOU TO FREE YOUR GODWIN SOUTH SUPPLIES IS VILLAGE FILLER JUST

# using key = [2, 1, 4, -3]
# translated = ROANOKE REST FILLER JUST WITH TRANSPORT SOUTH SUPPLIES ARE YOU TO FREE YOUR GODWIN GONE SNOW IS VILLAGE TO HEADING

# using key = [2, 1, 4, 3]
# translated = ROANOKE REST TO JUST WITH TRANSPORT GONE SUPPLIES ARE YOU TO FREE YOUR GODWIN SOUTH SNOW IS VILLAGE FILLER HEADING

# using key = [-2, -3, -1, -4]
# translated = HEADING VILLAGE IS FILLER SNOW GODWIN YOUR SOUTH FREE YOU ARE TO SUPPLIES TRANSPORT WITH GONE JUST REST ROANOKE TO

# using key = [-2, -3, -1, 4]
# translated = HEADING VILLAGE IS TO SNOW GODWIN YOUR GONE FREE YOU ARE TO SUPPLIES TRANSPORT WITH SOUTH JUST REST ROANOKE FILLER

# using key = [-2, -3, 1, -4]
# translated = JUST VILLAGE IS FILLER SUPPLIES GODWIN YOUR SOUTH FREE YOU ARE TO SNOW TRANSPORT WITH GONE HEADING REST ROANOKE TO

# using key = [-2, -3, 1, 4]
# translated = JUST VILLAGE IS TO SUPPLIES GODWIN YOUR GONE FREE YOU ARE TO SNOW TRANSPORT WITH SOUTH HEADING REST ROANOKE FILLER

# using key = [-2, 3, -1, -4]
# translated = HEADING VILLAGE ROANOKE FILLER SNOW GODWIN WITH SOUTH FREE YOU ARE TO SUPPLIES TRANSPORT YOUR GONE JUST REST IS TO

# using key = [-2, 3, -1, 4]
# translated = HEADING VILLAGE ROANOKE TO SNOW GODWIN WITH GONE FREE YOU ARE TO SUPPLIES TRANSPORT YOUR SOUTH JUST REST IS FILLER

# using key = [-2, 3, 1, -4]
# translated = JUST VILLAGE ROANOKE FILLER SUPPLIES GODWIN WITH SOUTH FREE YOU ARE TO SNOW TRANSPORT YOUR GONE HEADING REST IS TO

# using key = [-2, 3, 1, 4]
# translated = JUST VILLAGE ROANOKE TO SUPPLIES GODWIN WITH GONE FREE YOU ARE TO SNOW TRANSPORT YOUR SOUTH HEADING REST IS FILLER

# using key = [2, -3, -1, -4]
# translated = HEADING REST IS FILLER SNOW TRANSPORT YOUR SOUTH FREE YOU ARE TO SUPPLIES GODWIN WITH GONE JUST VILLAGE ROANOKE TO

# using key = [2, -3, -1, 4]
# translated = HEADING REST IS TO SNOW TRANSPORT YOUR GONE FREE YOU ARE TO SUPPLIES GODWIN WITH SOUTH JUST VILLAGE ROANOKE FILLER

# using key = [2, -3, 1, -4]
# translated = JUST REST IS FILLER SUPPLIES TRANSPORT YOUR SOUTH FREE YOU ARE TO SNOW GODWIN WITH GONE HEADING VILLAGE ROANOKE TO

# using key = [2, -3, 1, 4]
# translated = JUST REST IS TO SUPPLIES TRANSPORT YOUR GONE FREE YOU ARE TO SNOW GODWIN WITH SOUTH HEADING VILLAGE ROANOKE FILLER

# using key = [2, 3, -1, -4]
# translated = HEADING REST ROANOKE FILLER SNOW TRANSPORT WITH SOUTH FREE YOU ARE TO SUPPLIES GODWIN YOUR GONE JUST VILLAGE IS TO

# using key = [2, 3, -1, 4]
# translated = HEADING REST ROANOKE TO SNOW TRANSPORT WITH GONE FREE YOU ARE TO SUPPLIES GODWIN YOUR SOUTH JUST VILLAGE IS FILLER

# using key = [2, 3, 1, -4]
# translated = JUST REST ROANOKE FILLER SUPPLIES TRANSPORT WITH SOUTH FREE YOU ARE TO SNOW GODWIN YOUR GONE HEADING VILLAGE IS TO

# using key = [2, 3, 1, 4]
# translated = JUST REST ROANOKE TO SUPPLIES TRANSPORT WITH GONE FREE YOU ARE TO SNOW GODWIN YOUR SOUTH HEADING VILLAGE IS FILLER

# using key = [-2, -3, -4, -1]
# translated = FILLER VILLAGE IS HEADING SOUTH GODWIN YOUR SNOW TO YOU ARE FREE GONE TRANSPORT WITH SUPPLIES TO REST ROANOKE JUST

# using key = [-2, -3, -4, 1]
# translated = TO VILLAGE IS HEADING GONE GODWIN YOUR SNOW TO YOU ARE FREE SOUTH TRANSPORT WITH SUPPLIES FILLER REST ROANOKE JUST

# using key = [-2, -3, 4, -1]
# translated = FILLER VILLAGE IS JUST SOUTH GODWIN YOUR SUPPLIES TO YOU ARE FREE GONE TRANSPORT WITH SNOW TO REST ROANOKE HEADING

# using key = [-2, -3, 4, 1]
# translated = TO VILLAGE IS JUST GONE GODWIN YOUR SUPPLIES TO YOU ARE FREE SOUTH TRANSPORT WITH SNOW FILLER REST ROANOKE HEADING

# using key = [-2, 3, -4, -1]
# translated = FILLER VILLAGE ROANOKE HEADING SOUTH GODWIN WITH SNOW TO YOU ARE FREE GONE TRANSPORT YOUR SUPPLIES TO REST IS JUST

# using key = [-2, 3, -4, 1]
# translated = TO VILLAGE ROANOKE HEADING GONE GODWIN WITH SNOW TO YOU ARE FREE SOUTH TRANSPORT YOUR SUPPLIES FILLER REST IS JUST

# using key = [-2, 3, 4, -1]
# translated = FILLER VILLAGE ROANOKE JUST SOUTH GODWIN WITH SUPPLIES TO YOU ARE FREE GONE TRANSPORT YOUR SNOW TO REST IS HEADING

# using key = [-2, 3, 4, 1]
# translated = TO VILLAGE ROANOKE JUST GONE GODWIN WITH SUPPLIES TO YOU ARE FREE SOUTH TRANSPORT YOUR SNOW FILLER REST IS HEADING

# using key = [2, -3, -4, -1]
# translated = FILLER REST IS HEADING SOUTH TRANSPORT YOUR SNOW TO YOU ARE FREE GONE GODWIN WITH SUPPLIES TO VILLAGE ROANOKE JUST

# using key = [2, -3, -4, 1]
# translated = TO REST IS HEADING GONE TRANSPORT YOUR SNOW TO YOU ARE FREE SOUTH GODWIN WITH SUPPLIES FILLER VILLAGE ROANOKE JUST

# using key = [2, -3, 4, -1]
# translated = FILLER REST IS JUST SOUTH TRANSPORT YOUR SUPPLIES TO YOU ARE FREE GONE GODWIN WITH SNOW TO VILLAGE ROANOKE HEADING

# using key = [2, -3, 4, 1]
# translated = TO REST IS JUST GONE TRANSPORT YOUR SUPPLIES TO YOU ARE FREE SOUTH GODWIN WITH SNOW FILLER VILLAGE ROANOKE HEADING

# using key = [2, 3, -4, -1]
# translated = FILLER REST ROANOKE HEADING SOUTH TRANSPORT WITH SNOW TO YOU ARE FREE GONE GODWIN YOUR SUPPLIES TO VILLAGE IS JUST

# using key = [2, 3, -4, 1]
# translated = TO REST ROANOKE HEADING GONE TRANSPORT WITH SNOW TO YOU ARE FREE SOUTH GODWIN YOUR SUPPLIES FILLER VILLAGE IS JUST

# using key = [2, 3, 4, -1]
# translated = FILLER REST ROANOKE JUST SOUTH TRANSPORT WITH SUPPLIES TO YOU ARE FREE GONE GODWIN YOUR SNOW TO VILLAGE IS HEADING

# using key = [2, 3, 4, 1]
# translated = TO REST ROANOKE JUST GONE TRANSPORT WITH SUPPLIES TO YOU ARE FREE SOUTH GODWIN YOUR SNOW FILLER VILLAGE IS HEADING

# using key = [-2, -4, -1, -3]
# translated = HEADING VILLAGE FILLER IS SNOW GODWIN SOUTH YOUR FREE YOU TO ARE SUPPLIES TRANSPORT GONE WITH JUST REST TO ROANOKE

# using key = [-2, -4, -1, 3]
# translated = HEADING VILLAGE TO IS SNOW GODWIN GONE YOUR FREE YOU TO ARE SUPPLIES TRANSPORT SOUTH WITH JUST REST FILLER ROANOKE

# using key = [-2, -4, 1, -3]
# translated = JUST VILLAGE FILLER IS SUPPLIES GODWIN SOUTH YOUR FREE YOU TO ARE SNOW TRANSPORT GONE WITH HEADING REST TO ROANOKE

# using key = [-2, -4, 1, 3]
# translated = JUST VILLAGE TO IS SUPPLIES GODWIN GONE YOUR FREE YOU TO ARE SNOW TRANSPORT SOUTH WITH HEADING REST FILLER ROANOKE

# using key = [-2, 4, -1, -3]
# translated = HEADING VILLAGE FILLER ROANOKE SNOW GODWIN SOUTH WITH FREE YOU TO ARE SUPPLIES TRANSPORT GONE YOUR JUST REST TO IS

# using key = [-2, 4, -1, 3]
# translated = HEADING VILLAGE TO ROANOKE SNOW GODWIN GONE WITH FREE YOU TO ARE SUPPLIES TRANSPORT SOUTH YOUR JUST REST FILLER IS

# using key = [-2, 4, 1, -3]
# translated = JUST VILLAGE FILLER ROANOKE SUPPLIES GODWIN SOUTH WITH FREE YOU TO ARE SNOW TRANSPORT GONE YOUR HEADING REST TO IS

# using key = [-2, 4, 1, 3]
# translated = JUST VILLAGE TO ROANOKE SUPPLIES GODWIN GONE WITH FREE YOU TO ARE SNOW TRANSPORT SOUTH YOUR HEADING REST FILLER IS

# using key = [2, -4, -1, -3]
# translated = HEADING REST FILLER IS SNOW TRANSPORT SOUTH YOUR FREE YOU TO ARE SUPPLIES GODWIN GONE WITH JUST VILLAGE TO ROANOKE

# using key = [2, -4, -1, 3]
# translated = HEADING REST TO IS SNOW TRANSPORT GONE YOUR FREE YOU TO ARE SUPPLIES GODWIN SOUTH WITH JUST VILLAGE FILLER ROANOKE

# using key = [2, -4, 1, -3]
# translated = JUST REST FILLER IS SUPPLIES TRANSPORT SOUTH YOUR FREE YOU TO ARE SNOW GODWIN GONE WITH HEADING VILLAGE TO ROANOKE

# using key = [2, -4, 1, 3]
# translated = JUST REST TO IS SUPPLIES TRANSPORT GONE YOUR FREE YOU TO ARE SNOW GODWIN SOUTH WITH HEADING VILLAGE FILLER ROANOKE

# using key = [2, 4, -1, -3]
# translated = HEADING REST FILLER ROANOKE SNOW TRANSPORT SOUTH WITH FREE YOU TO ARE SUPPLIES GODWIN GONE YOUR JUST VILLAGE TO IS

# using key = [2, 4, -1, 3]
# translated = HEADING REST TO ROANOKE SNOW TRANSPORT GONE WITH FREE YOU TO ARE SUPPLIES GODWIN SOUTH YOUR JUST VILLAGE FILLER IS

# using key = [2, 4, 1, -3]
# translated = JUST REST FILLER ROANOKE SUPPLIES TRANSPORT SOUTH WITH FREE YOU TO ARE SNOW GODWIN GONE YOUR HEADING VILLAGE TO IS

# using key = [2, 4, 1, 3]
# translated = JUST REST TO ROANOKE SUPPLIES TRANSPORT GONE WITH FREE YOU TO ARE SNOW GODWIN SOUTH YOUR HEADING VILLAGE FILLER IS

# using key = [-2, -4, -3, -1]
# translated = FILLER VILLAGE HEADING IS SOUTH GODWIN SNOW YOUR TO YOU FREE ARE GONE TRANSPORT SUPPLIES WITH TO REST JUST ROANOKE

# using key = [-2, -4, -3, 1]
# translated = TO VILLAGE HEADING IS GONE GODWIN SNOW YOUR TO YOU FREE ARE SOUTH TRANSPORT SUPPLIES WITH FILLER REST JUST ROANOKE

# using key = [-2, -4, 3, -1]
# translated = FILLER VILLAGE JUST IS SOUTH GODWIN SUPPLIES YOUR TO YOU FREE ARE GONE TRANSPORT SNOW WITH TO REST HEADING ROANOKE

# using key = [-2, -4, 3, 1]
# translated = TO VILLAGE JUST IS GONE GODWIN SUPPLIES YOUR TO YOU FREE ARE SOUTH TRANSPORT SNOW WITH FILLER REST HEADING ROANOKE

# using key = [-2, 4, -3, -1]
# translated = FILLER VILLAGE HEADING ROANOKE SOUTH GODWIN SNOW WITH TO YOU FREE ARE GONE TRANSPORT SUPPLIES YOUR TO REST JUST IS

# using key = [-2, 4, -3, 1]
# translated = TO VILLAGE HEADING ROANOKE GONE GODWIN SNOW WITH TO YOU FREE ARE SOUTH TRANSPORT SUPPLIES YOUR FILLER REST JUST IS

# using key = [-2, 4, 3, -1]
# translated = FILLER VILLAGE JUST ROANOKE SOUTH GODWIN SUPPLIES WITH TO YOU FREE ARE GONE TRANSPORT SNOW YOUR TO REST HEADING IS

# using key = [-2, 4, 3, 1]
# translated = TO VILLAGE JUST ROANOKE GONE GODWIN SUPPLIES WITH TO YOU FREE ARE SOUTH TRANSPORT SNOW YOUR FILLER REST HEADING IS

# using key = [2, -4, -3, -1]
# translated = FILLER REST HEADING IS SOUTH TRANSPORT SNOW YOUR TO YOU FREE ARE GONE GODWIN SUPPLIES WITH TO VILLAGE JUST ROANOKE

# using key = [2, -4, -3, 1]
# translated = TO REST HEADING IS GONE TRANSPORT SNOW YOUR TO YOU FREE ARE SOUTH GODWIN SUPPLIES WITH FILLER VILLAGE JUST ROANOKE

# using key = [2, -4, 3, -1]
# translated = FILLER REST JUST IS SOUTH TRANSPORT SUPPLIES YOUR TO YOU FREE ARE GONE GODWIN SNOW WITH TO VILLAGE HEADING ROANOKE

# using key = [2, -4, 3, 1]
# translated = TO REST JUST IS GONE TRANSPORT SUPPLIES YOUR TO YOU FREE ARE SOUTH GODWIN SNOW WITH FILLER VILLAGE HEADING ROANOKE

# using key = [2, 4, -3, -1]
# translated = FILLER REST HEADING ROANOKE SOUTH TRANSPORT SNOW WITH TO YOU FREE ARE GONE GODWIN SUPPLIES YOUR TO VILLAGE JUST IS

# using key = [2, 4, -3, 1]
# translated = TO REST HEADING ROANOKE GONE TRANSPORT SNOW WITH TO YOU FREE ARE SOUTH GODWIN SUPPLIES YOUR FILLER VILLAGE JUST IS

# using key = [2, 4, 3, -1]
# translated = FILLER REST JUST ROANOKE SOUTH TRANSPORT SUPPLIES WITH TO YOU FREE ARE GONE GODWIN SNOW YOUR TO VILLAGE HEADING IS

# using key = [2, 4, 3, 1]
# translated = TO REST JUST ROANOKE GONE TRANSPORT SUPPLIES WITH TO YOU FREE ARE SOUTH GODWIN SNOW YOUR FILLER VILLAGE HEADING IS

# using key = [-3, -1, -2, -4]
# translated = IS HEADING VILLAGE FILLER YOUR SNOW GODWIN SOUTH ARE FREE YOU TO WITH SUPPLIES TRANSPORT GONE ROANOKE JUST REST TO

# using key = [-3, -1, -2, 4]
# translated = IS HEADING VILLAGE TO YOUR SNOW GODWIN GONE ARE FREE YOU TO WITH SUPPLIES TRANSPORT SOUTH ROANOKE JUST REST FILLER

# using key = [-3, -1, 2, -4]
# translated = IS JUST VILLAGE FILLER YOUR SUPPLIES GODWIN SOUTH ARE FREE YOU TO WITH SNOW TRANSPORT GONE ROANOKE HEADING REST TO

# using key = [-3, -1, 2, 4]
# translated = IS JUST VILLAGE TO YOUR SUPPLIES GODWIN GONE ARE FREE YOU TO WITH SNOW TRANSPORT SOUTH ROANOKE HEADING REST FILLER

# using key = [-3, 1, -2, -4]
# translated = ROANOKE HEADING VILLAGE FILLER WITH SNOW GODWIN SOUTH ARE FREE YOU TO YOUR SUPPLIES TRANSPORT GONE IS JUST REST TO

# using key = [-3, 1, -2, 4]
# translated = ROANOKE HEADING VILLAGE TO WITH SNOW GODWIN GONE ARE FREE YOU TO YOUR SUPPLIES TRANSPORT SOUTH IS JUST REST FILLER

# using key = [-3, 1, 2, -4]
# translated = ROANOKE JUST VILLAGE FILLER WITH SUPPLIES GODWIN SOUTH ARE FREE YOU TO YOUR SNOW TRANSPORT GONE IS HEADING REST TO

# using key = [-3, 1, 2, 4]
# translated = ROANOKE JUST VILLAGE TO WITH SUPPLIES GODWIN GONE ARE FREE YOU TO YOUR SNOW TRANSPORT SOUTH IS HEADING REST FILLER

# using key = [3, -1, -2, -4]
# translated = IS HEADING REST FILLER YOUR SNOW TRANSPORT SOUTH ARE FREE YOU TO WITH SUPPLIES GODWIN GONE ROANOKE JUST VILLAGE TO

# using key = [3, -1, -2, 4]
# translated = IS HEADING REST TO YOUR SNOW TRANSPORT GONE ARE FREE YOU TO WITH SUPPLIES GODWIN SOUTH ROANOKE JUST VILLAGE FILLER

# using key = [3, -1, 2, -4]
# translated = IS JUST REST FILLER YOUR SUPPLIES TRANSPORT SOUTH ARE FREE YOU TO WITH SNOW GODWIN GONE ROANOKE HEADING VILLAGE TO

# using key = [3, -1, 2, 4]
# translated = IS JUST REST TO YOUR SUPPLIES TRANSPORT GONE ARE FREE YOU TO WITH SNOW GODWIN SOUTH ROANOKE HEADING VILLAGE FILLER

# using key = [3, 1, -2, -4]
# translated = ROANOKE HEADING REST FILLER WITH SNOW TRANSPORT SOUTH ARE FREE YOU TO YOUR SUPPLIES GODWIN GONE IS JUST VILLAGE TO

# using key = [3, 1, -2, 4]
# translated = ROANOKE HEADING REST TO WITH SNOW TRANSPORT GONE ARE FREE YOU TO YOUR SUPPLIES GODWIN SOUTH IS JUST VILLAGE FILLER

# using key = [3, 1, 2, -4]
# translated = ROANOKE JUST REST FILLER WITH SUPPLIES TRANSPORT SOUTH ARE FREE YOU TO YOUR SNOW GODWIN GONE IS HEADING VILLAGE TO

# using key = [3, 1, 2, 4]
# translated = ROANOKE JUST REST TO WITH SUPPLIES TRANSPORT GONE ARE FREE YOU TO YOUR SNOW GODWIN SOUTH IS HEADING VILLAGE FILLER

# using key = [-3, -1, -4, -2]
# translated = IS FILLER VILLAGE HEADING YOUR SOUTH GODWIN SNOW ARE TO YOU FREE WITH GONE TRANSPORT SUPPLIES ROANOKE TO REST JUST

# using key = [-3, -1, -4, 2]
# translated = IS TO VILLAGE HEADING YOUR GONE GODWIN SNOW ARE TO YOU FREE WITH SOUTH TRANSPORT SUPPLIES ROANOKE FILLER REST JUST

# using key = [-3, -1, 4, -2]
# translated = IS FILLER VILLAGE JUST YOUR SOUTH GODWIN SUPPLIES ARE TO YOU FREE WITH GONE TRANSPORT SNOW ROANOKE TO REST HEADING

# using key = [-3, -1, 4, 2]
# translated = IS TO VILLAGE JUST YOUR GONE GODWIN SUPPLIES ARE TO YOU FREE WITH SOUTH TRANSPORT SNOW ROANOKE FILLER REST HEADING

# using key = [-3, 1, -4, -2]
# translated = ROANOKE FILLER VILLAGE HEADING WITH SOUTH GODWIN SNOW ARE TO YOU FREE YOUR GONE TRANSPORT SUPPLIES IS TO REST JUST

# using key = [-3, 1, -4, 2]
# translated = ROANOKE TO VILLAGE HEADING WITH GONE GODWIN SNOW ARE TO YOU FREE YOUR SOUTH TRANSPORT SUPPLIES IS FILLER REST JUST

# using key = [-3, 1, 4, -2]
# translated = ROANOKE FILLER VILLAGE JUST WITH SOUTH GODWIN SUPPLIES ARE TO YOU FREE YOUR GONE TRANSPORT SNOW IS TO REST HEADING

# using key = [-3, 1, 4, 2]
# translated = ROANOKE TO VILLAGE JUST WITH GONE GODWIN SUPPLIES ARE TO YOU FREE YOUR SOUTH TRANSPORT SNOW IS FILLER REST HEADING

# using key = [3, -1, -4, -2]
# translated = IS FILLER REST HEADING YOUR SOUTH TRANSPORT SNOW ARE TO YOU FREE WITH GONE GODWIN SUPPLIES ROANOKE TO VILLAGE JUST

# using key = [3, -1, -4, 2]
# translated = IS TO REST HEADING YOUR GONE TRANSPORT SNOW ARE TO YOU FREE WITH SOUTH GODWIN SUPPLIES ROANOKE FILLER VILLAGE JUST

# using key = [3, -1, 4, -2]
# translated = IS FILLER REST JUST YOUR SOUTH TRANSPORT SUPPLIES ARE TO YOU FREE WITH GONE GODWIN SNOW ROANOKE TO VILLAGE HEADING

# using key = [3, -1, 4, 2]
# translated = IS TO REST JUST YOUR GONE TRANSPORT SUPPLIES ARE TO YOU FREE WITH SOUTH GODWIN SNOW ROANOKE FILLER VILLAGE HEADING

# using key = [3, 1, -4, -2]
# translated = ROANOKE FILLER REST HEADING WITH SOUTH TRANSPORT SNOW ARE TO YOU FREE YOUR GONE GODWIN SUPPLIES IS TO VILLAGE JUST

# using key = [3, 1, -4, 2]
# translated = ROANOKE TO REST HEADING WITH GONE TRANSPORT SNOW ARE TO YOU FREE YOUR SOUTH GODWIN SUPPLIES IS FILLER VILLAGE JUST

# using key = [3, 1, 4, -2]
# translated = ROANOKE FILLER REST JUST WITH SOUTH TRANSPORT SUPPLIES ARE TO YOU FREE YOUR GONE GODWIN SNOW IS TO VILLAGE HEADING

# using key = [3, 1, 4, 2]
# translated = ROANOKE TO REST JUST WITH GONE TRANSPORT SUPPLIES ARE TO YOU FREE YOUR SOUTH GODWIN SNOW IS FILLER VILLAGE HEADING

# using key = [-3, -2, -1, -4]
# translated = HEADING IS VILLAGE FILLER SNOW YOUR GODWIN SOUTH FREE ARE YOU TO SUPPLIES WITH TRANSPORT GONE JUST ROANOKE REST TO

# using key = [-3, -2, -1, 4]
# translated = HEADING IS VILLAGE TO SNOW YOUR GODWIN GONE FREE ARE YOU TO SUPPLIES WITH TRANSPORT SOUTH JUST ROANOKE REST FILLER

# using key = [-3, -2, 1, -4]
# translated = JUST IS VILLAGE FILLER SUPPLIES YOUR GODWIN SOUTH FREE ARE YOU TO SNOW WITH TRANSPORT GONE HEADING ROANOKE REST TO

# using key = [-3, -2, 1, 4]
# translated = JUST IS VILLAGE TO SUPPLIES YOUR GODWIN GONE FREE ARE YOU TO SNOW WITH TRANSPORT SOUTH HEADING ROANOKE REST FILLER

# using key = [-3, 2, -1, -4]
# translated = HEADING ROANOKE VILLAGE FILLER SNOW WITH GODWIN SOUTH FREE ARE YOU TO SUPPLIES YOUR TRANSPORT GONE JUST IS REST TO

# using key = [-3, 2, -1, 4]
# translated = HEADING ROANOKE VILLAGE TO SNOW WITH GODWIN GONE FREE ARE YOU TO SUPPLIES YOUR TRANSPORT SOUTH JUST IS REST FILLER

# using key = [-3, 2, 1, -4]
# translated = JUST ROANOKE VILLAGE FILLER SUPPLIES WITH GODWIN SOUTH FREE ARE YOU TO SNOW YOUR TRANSPORT GONE HEADING IS REST TO

# using key = [-3, 2, 1, 4]
# translated = JUST ROANOKE VILLAGE TO SUPPLIES WITH GODWIN GONE FREE ARE YOU TO SNOW YOUR TRANSPORT SOUTH HEADING IS REST FILLER

# using key = [3, -2, -1, -4]
# translated = HEADING IS REST FILLER SNOW YOUR TRANSPORT SOUTH FREE ARE YOU TO SUPPLIES WITH GODWIN GONE JUST ROANOKE VILLAGE TO

# using key = [3, -2, -1, 4]
# translated = HEADING IS REST TO SNOW YOUR TRANSPORT GONE FREE ARE YOU TO SUPPLIES WITH GODWIN SOUTH JUST ROANOKE VILLAGE FILLER

# using key = [3, -2, 1, -4]
# translated = JUST IS REST FILLER SUPPLIES YOUR TRANSPORT SOUTH FREE ARE YOU TO SNOW WITH GODWIN GONE HEADING ROANOKE VILLAGE TO

# using key = [3, -2, 1, 4]
# translated = JUST IS REST TO SUPPLIES YOUR TRANSPORT GONE FREE ARE YOU TO SNOW WITH GODWIN SOUTH HEADING ROANOKE VILLAGE FILLER

# using key = [3, 2, -1, -4]
# translated = HEADING ROANOKE REST FILLER SNOW WITH TRANSPORT SOUTH FREE ARE YOU TO SUPPLIES YOUR GODWIN GONE JUST IS VILLAGE TO

# using key = [3, 2, -1, 4]
# translated = HEADING ROANOKE REST TO SNOW WITH TRANSPORT GONE FREE ARE YOU TO SUPPLIES YOUR GODWIN SOUTH JUST IS VILLAGE FILLER

# using key = [3, 2, 1, -4]
# translated = JUST ROANOKE REST FILLER SUPPLIES WITH TRANSPORT SOUTH FREE ARE YOU TO SNOW YOUR GODWIN GONE HEADING IS VILLAGE TO

# using key = [3, 2, 1, 4]
# translated = JUST ROANOKE REST TO SUPPLIES WITH TRANSPORT GONE FREE ARE YOU TO SNOW YOUR GODWIN SOUTH HEADING IS VILLAGE FILLER

# using key = [-3, -2, -4, -1]
# translated = FILLER IS VILLAGE HEADING SOUTH YOUR GODWIN SNOW TO ARE YOU FREE GONE WITH TRANSPORT SUPPLIES TO ROANOKE REST JUST

# using key = [-3, -2, -4, 1]
# translated = TO IS VILLAGE HEADING GONE YOUR GODWIN SNOW TO ARE YOU FREE SOUTH WITH TRANSPORT SUPPLIES FILLER ROANOKE REST JUST

# using key = [-3, -2, 4, -1]
# translated = FILLER IS VILLAGE JUST SOUTH YOUR GODWIN SUPPLIES TO ARE YOU FREE GONE WITH TRANSPORT SNOW TO ROANOKE REST HEADING

# using key = [-3, -2, 4, 1]
# translated = TO IS VILLAGE JUST GONE YOUR GODWIN SUPPLIES TO ARE YOU FREE SOUTH WITH TRANSPORT SNOW FILLER ROANOKE REST HEADING

# using key = [-3, 2, -4, -1]
# translated = FILLER ROANOKE VILLAGE HEADING SOUTH WITH GODWIN SNOW TO ARE YOU FREE GONE YOUR TRANSPORT SUPPLIES TO IS REST JUST

# using key = [-3, 2, -4, 1]
# translated = TO ROANOKE VILLAGE HEADING GONE WITH GODWIN SNOW TO ARE YOU FREE SOUTH YOUR TRANSPORT SUPPLIES FILLER IS REST JUST

# using key = [-3, 2, 4, -1]
# translated = FILLER ROANOKE VILLAGE JUST SOUTH WITH GODWIN SUPPLIES TO ARE YOU FREE GONE YOUR TRANSPORT SNOW TO IS REST HEADING

# using key = [-3, 2, 4, 1]
# translated = TO ROANOKE VILLAGE JUST GONE WITH GODWIN SUPPLIES TO ARE YOU FREE SOUTH YOUR TRANSPORT SNOW FILLER IS REST HEADING

# using key = [3, -2, -4, -1]
# translated = FILLER IS REST HEADING SOUTH YOUR TRANSPORT SNOW TO ARE YOU FREE GONE WITH GODWIN SUPPLIES TO ROANOKE VILLAGE JUST

# using key = [3, -2, -4, 1]
# translated = TO IS REST HEADING GONE YOUR TRANSPORT SNOW TO ARE YOU FREE SOUTH WITH GODWIN SUPPLIES FILLER ROANOKE VILLAGE JUST

# using key = [3, -2, 4, -1]
# translated = FILLER IS REST JUST SOUTH YOUR TRANSPORT SUPPLIES TO ARE YOU FREE GONE WITH GODWIN SNOW TO ROANOKE VILLAGE HEADING

# using key = [3, -2, 4, 1]
# translated = TO IS REST JUST GONE YOUR TRANSPORT SUPPLIES TO ARE YOU FREE SOUTH WITH GODWIN SNOW FILLER ROANOKE VILLAGE HEADING

# using key = [3, 2, -4, -1]
# translated = FILLER ROANOKE REST HEADING SOUTH WITH TRANSPORT SNOW TO ARE YOU FREE GONE YOUR GODWIN SUPPLIES TO IS VILLAGE JUST

# using key = [3, 2, -4, 1]
# translated = TO ROANOKE REST HEADING GONE WITH TRANSPORT SNOW TO ARE YOU FREE SOUTH YOUR GODWIN SUPPLIES FILLER IS VILLAGE JUST

# using key = [3, 2, 4, -1]
# translated = FILLER ROANOKE REST JUST SOUTH WITH TRANSPORT SUPPLIES TO ARE YOU FREE GONE YOUR GODWIN SNOW TO IS VILLAGE HEADING

# using key = [3, 2, 4, 1]
# translated = TO ROANOKE REST JUST GONE WITH TRANSPORT SUPPLIES TO ARE YOU FREE SOUTH YOUR GODWIN SNOW FILLER IS VILLAGE HEADING

# using key = [-3, -4, -1, -2]
# translated = HEADING FILLER VILLAGE IS SNOW SOUTH GODWIN YOUR FREE TO YOU ARE SUPPLIES GONE TRANSPORT WITH JUST TO REST ROANOKE

# using key = [-3, -4, -1, 2]
# translated = HEADING TO VILLAGE IS SNOW GONE GODWIN YOUR FREE TO YOU ARE SUPPLIES SOUTH TRANSPORT WITH JUST FILLER REST ROANOKE

# using key = [-3, -4, 1, -2]
# translated = JUST FILLER VILLAGE IS SUPPLIES SOUTH GODWIN YOUR FREE TO YOU ARE SNOW GONE TRANSPORT WITH HEADING TO REST ROANOKE

# using key = [-3, -4, 1, 2]
# translated = JUST TO VILLAGE IS SUPPLIES GONE GODWIN YOUR FREE TO YOU ARE SNOW SOUTH TRANSPORT WITH HEADING FILLER REST ROANOKE

# using key = [-3, 4, -1, -2]
# translated = HEADING FILLER VILLAGE ROANOKE SNOW SOUTH GODWIN WITH FREE TO YOU ARE SUPPLIES GONE TRANSPORT YOUR JUST TO REST IS

# using key = [-3, 4, -1, 2]
# translated = HEADING TO VILLAGE ROANOKE SNOW GONE GODWIN WITH FREE TO YOU ARE SUPPLIES SOUTH TRANSPORT YOUR JUST FILLER REST IS

# using key = [-3, 4, 1, -2]
# translated = JUST FILLER VILLAGE ROANOKE SUPPLIES SOUTH GODWIN WITH FREE TO YOU ARE SNOW GONE TRANSPORT YOUR HEADING TO REST IS

# using key = [-3, 4, 1, 2]
# translated = JUST TO VILLAGE ROANOKE SUPPLIES GONE GODWIN WITH FREE TO YOU ARE SNOW SOUTH TRANSPORT YOUR HEADING FILLER REST IS

# using key = [3, -4, -1, -2]
# translated = HEADING FILLER REST IS SNOW SOUTH TRANSPORT YOUR FREE TO YOU ARE SUPPLIES GONE GODWIN WITH JUST TO VILLAGE ROANOKE

# using key = [3, -4, -1, 2]
# translated = HEADING TO REST IS SNOW GONE TRANSPORT YOUR FREE TO YOU ARE SUPPLIES SOUTH GODWIN WITH JUST FILLER VILLAGE ROANOKE

# using key = [3, -4, 1, -2]
# translated = JUST FILLER REST IS SUPPLIES SOUTH TRANSPORT YOUR FREE TO YOU ARE SNOW GONE GODWIN WITH HEADING TO VILLAGE ROANOKE

# using key = [3, -4, 1, 2]
# translated = JUST TO REST IS SUPPLIES GONE TRANSPORT YOUR FREE TO YOU ARE SNOW SOUTH GODWIN WITH HEADING FILLER VILLAGE ROANOKE

# using key = [3, 4, -1, -2]
# translated = HEADING FILLER REST ROANOKE SNOW SOUTH TRANSPORT WITH FREE TO YOU ARE SUPPLIES GONE GODWIN YOUR JUST TO VILLAGE IS

# using key = [3, 4, -1, 2]
# translated = HEADING TO REST ROANOKE SNOW GONE TRANSPORT WITH FREE TO YOU ARE SUPPLIES SOUTH GODWIN YOUR JUST FILLER VILLAGE IS

# using key = [3, 4, 1, -2]
# translated = JUST FILLER REST ROANOKE SUPPLIES SOUTH TRANSPORT WITH FREE TO YOU ARE SNOW GONE GODWIN YOUR HEADING TO VILLAGE IS

# using key = [3, 4, 1, 2]
# translated = JUST TO REST ROANOKE SUPPLIES GONE TRANSPORT WITH FREE TO YOU ARE SNOW SOUTH GODWIN YOUR HEADING FILLER VILLAGE IS

# using key = [-3, -4, -2, -1]
# translated = FILLER HEADING VILLAGE IS SOUTH SNOW GODWIN YOUR TO FREE YOU ARE GONE SUPPLIES TRANSPORT WITH TO JUST REST ROANOKE

# using key = [-3, -4, -2, 1]
# translated = TO HEADING VILLAGE IS GONE SNOW GODWIN YOUR TO FREE YOU ARE SOUTH SUPPLIES TRANSPORT WITH FILLER JUST REST ROANOKE

# using key = [-3, -4, 2, -1]
# translated = FILLER JUST VILLAGE IS SOUTH SUPPLIES GODWIN YOUR TO FREE YOU ARE GONE SNOW TRANSPORT WITH TO HEADING REST ROANOKE

# using key = [-3, -4, 2, 1]
# translated = TO JUST VILLAGE IS GONE SUPPLIES GODWIN YOUR TO FREE YOU ARE SOUTH SNOW TRANSPORT WITH FILLER HEADING REST ROANOKE

# using key = [-3, 4, -2, -1]
# translated = FILLER HEADING VILLAGE ROANOKE SOUTH SNOW GODWIN WITH TO FREE YOU ARE GONE SUPPLIES TRANSPORT YOUR TO JUST REST IS

# using key = [-3, 4, -2, 1]
# translated = TO HEADING VILLAGE ROANOKE GONE SNOW GODWIN WITH TO FREE YOU ARE SOUTH SUPPLIES TRANSPORT YOUR FILLER JUST REST IS

# using key = [-3, 4, 2, -1]
# translated = FILLER JUST VILLAGE ROANOKE SOUTH SUPPLIES GODWIN WITH TO FREE YOU ARE GONE SNOW TRANSPORT YOUR TO HEADING REST IS

# using key = [-3, 4, 2, 1]
# translated = TO JUST VILLAGE ROANOKE GONE SUPPLIES GODWIN WITH TO FREE YOU ARE SOUTH SNOW TRANSPORT YOUR FILLER HEADING REST IS

# using key = [3, -4, -2, -1]
# translated = FILLER HEADING REST IS SOUTH SNOW TRANSPORT YOUR TO FREE YOU ARE GONE SUPPLIES GODWIN WITH TO JUST VILLAGE ROANOKE

# using key = [3, -4, -2, 1]
# translated = TO HEADING REST IS GONE SNOW TRANSPORT YOUR TO FREE YOU ARE SOUTH SUPPLIES GODWIN WITH FILLER JUST VILLAGE ROANOKE

# using key = [3, -4, 2, -1]
# translated = FILLER JUST REST IS SOUTH SUPPLIES TRANSPORT YOUR TO FREE YOU ARE GONE SNOW GODWIN WITH TO HEADING VILLAGE ROANOKE

# using key = [3, -4, 2, 1]
# translated = TO JUST REST IS GONE SUPPLIES TRANSPORT YOUR TO FREE YOU ARE SOUTH SNOW GODWIN WITH FILLER HEADING VILLAGE ROANOKE

# using key = [3, 4, -2, -1]
# translated = FILLER HEADING REST ROANOKE SOUTH SNOW TRANSPORT WITH TO FREE YOU ARE GONE SUPPLIES GODWIN YOUR TO JUST VILLAGE IS

# using key = [3, 4, -2, 1]
# translated = TO HEADING REST ROANOKE GONE SNOW TRANSPORT WITH TO FREE YOU ARE SOUTH SUPPLIES GODWIN YOUR FILLER JUST VILLAGE IS

# using key = [3, 4, 2, -1]
# translated = FILLER JUST REST ROANOKE SOUTH SUPPLIES TRANSPORT WITH TO FREE YOU ARE GONE SNOW GODWIN YOUR TO HEADING VILLAGE IS

# using key = [3, 4, 2, 1]
# translated = TO JUST REST ROANOKE GONE SUPPLIES TRANSPORT WITH TO FREE YOU ARE SOUTH SNOW GODWIN YOUR FILLER HEADING VILLAGE IS

# using key = [-4, -1, -2, -3]
# translated = IS HEADING FILLER VILLAGE YOUR SNOW SOUTH GODWIN ARE FREE TO YOU WITH SUPPLIES GONE TRANSPORT ROANOKE JUST TO REST

# using key = [-4, -1, -2, 3]
# translated = IS HEADING TO VILLAGE YOUR SNOW GONE GODWIN ARE FREE TO YOU WITH SUPPLIES SOUTH TRANSPORT ROANOKE JUST FILLER REST

# using key = [-4, -1, 2, -3]
# translated = IS JUST FILLER VILLAGE YOUR SUPPLIES SOUTH GODWIN ARE FREE TO YOU WITH SNOW GONE TRANSPORT ROANOKE HEADING TO REST

# using key = [-4, -1, 2, 3]
# translated = IS JUST TO VILLAGE YOUR SUPPLIES GONE GODWIN ARE FREE TO YOU WITH SNOW SOUTH TRANSPORT ROANOKE HEADING FILLER REST

# using key = [-4, 1, -2, -3]
# translated = ROANOKE HEADING FILLER VILLAGE WITH SNOW SOUTH GODWIN ARE FREE TO YOU YOUR SUPPLIES GONE TRANSPORT IS JUST TO REST

# using key = [-4, 1, -2, 3]
# translated = ROANOKE HEADING TO VILLAGE WITH SNOW GONE GODWIN ARE FREE TO YOU YOUR SUPPLIES SOUTH TRANSPORT IS JUST FILLER REST

# using key = [-4, 1, 2, -3]
# translated = ROANOKE JUST FILLER VILLAGE WITH SUPPLIES SOUTH GODWIN ARE FREE TO YOU YOUR SNOW GONE TRANSPORT IS HEADING TO REST

# using key = [-4, 1, 2, 3]
# translated = ROANOKE JUST TO VILLAGE WITH SUPPLIES GONE GODWIN ARE FREE TO YOU YOUR SNOW SOUTH TRANSPORT IS HEADING FILLER REST

# using key = [4, -1, -2, -3]
# translated = IS HEADING FILLER REST YOUR SNOW SOUTH TRANSPORT ARE FREE TO YOU WITH SUPPLIES GONE GODWIN ROANOKE JUST TO VILLAGE

# using key = [4, -1, -2, 3]
# translated = IS HEADING TO REST YOUR SNOW GONE TRANSPORT ARE FREE TO YOU WITH SUPPLIES SOUTH GODWIN ROANOKE JUST FILLER VILLAGE

# using key = [4, -1, 2, -3]
# translated = IS JUST FILLER REST YOUR SUPPLIES SOUTH TRANSPORT ARE FREE TO YOU WITH SNOW GONE GODWIN ROANOKE HEADING TO VILLAGE

# using key = [4, -1, 2, 3]
# translated = IS JUST TO REST YOUR SUPPLIES GONE TRANSPORT ARE FREE TO YOU WITH SNOW SOUTH GODWIN ROANOKE HEADING FILLER VILLAGE

# using key = [4, 1, -2, -3]
# translated = ROANOKE HEADING FILLER REST WITH SNOW SOUTH TRANSPORT ARE FREE TO YOU YOUR SUPPLIES GONE GODWIN IS JUST TO VILLAGE

# using key = [4, 1, -2, 3]
# translated = ROANOKE HEADING TO REST WITH SNOW GONE TRANSPORT ARE FREE TO YOU YOUR SUPPLIES SOUTH GODWIN IS JUST FILLER VILLAGE

# using key = [4, 1, 2, -3]
# translated = ROANOKE JUST FILLER REST WITH SUPPLIES SOUTH TRANSPORT ARE FREE TO YOU YOUR SNOW GONE GODWIN IS HEADING TO VILLAGE

# using key = [4, 1, 2, 3]
# translated = ROANOKE JUST TO REST WITH SUPPLIES GONE TRANSPORT ARE FREE TO YOU YOUR SNOW SOUTH GODWIN IS HEADING FILLER VILLAGE

# using key = [-4, -1, -3, -2]
# translated = IS FILLER HEADING VILLAGE YOUR SOUTH SNOW GODWIN ARE TO FREE YOU WITH GONE SUPPLIES TRANSPORT ROANOKE TO JUST REST

# using key = [-4, -1, -3, 2]
# translated = IS TO HEADING VILLAGE YOUR GONE SNOW GODWIN ARE TO FREE YOU WITH SOUTH SUPPLIES TRANSPORT ROANOKE FILLER JUST REST

# using key = [-4, -1, 3, -2]
# translated = IS FILLER JUST VILLAGE YOUR SOUTH SUPPLIES GODWIN ARE TO FREE YOU WITH GONE SNOW TRANSPORT ROANOKE TO HEADING REST

# using key = [-4, -1, 3, 2]
# translated = IS TO JUST VILLAGE YOUR GONE SUPPLIES GODWIN ARE TO FREE YOU WITH SOUTH SNOW TRANSPORT ROANOKE FILLER HEADING REST

# using key = [-4, 1, -3, -2]
# translated = ROANOKE FILLER HEADING VILLAGE WITH SOUTH SNOW GODWIN ARE TO FREE YOU YOUR GONE SUPPLIES TRANSPORT IS TO JUST REST

# using key = [-4, 1, -3, 2]
# translated = ROANOKE TO HEADING VILLAGE WITH GONE SNOW GODWIN ARE TO FREE YOU YOUR SOUTH SUPPLIES TRANSPORT IS FILLER JUST REST

# using key = [-4, 1, 3, -2]
# translated = ROANOKE FILLER JUST VILLAGE WITH SOUTH SUPPLIES GODWIN ARE TO FREE YOU YOUR GONE SNOW TRANSPORT IS TO HEADING REST

# using key = [-4, 1, 3, 2]
# translated = ROANOKE TO JUST VILLAGE WITH GONE SUPPLIES GODWIN ARE TO FREE YOU YOUR SOUTH SNOW TRANSPORT IS FILLER HEADING REST

# using key = [4, -1, -3, -2]
# translated = IS FILLER HEADING REST YOUR SOUTH SNOW TRANSPORT ARE TO FREE YOU WITH GONE SUPPLIES GODWIN ROANOKE TO JUST VILLAGE

# using key = [4, -1, -3, 2]
# translated = IS TO HEADING REST YOUR GONE SNOW TRANSPORT ARE TO FREE YOU WITH SOUTH SUPPLIES GODWIN ROANOKE FILLER JUST VILLAGE

# using key = [4, -1, 3, -2]
# translated = IS FILLER JUST REST YOUR SOUTH SUPPLIES TRANSPORT ARE TO FREE YOU WITH GONE SNOW GODWIN ROANOKE TO HEADING VILLAGE

# using key = [4, -1, 3, 2]
# translated = IS TO JUST REST YOUR GONE SUPPLIES TRANSPORT ARE TO FREE YOU WITH SOUTH SNOW GODWIN ROANOKE FILLER HEADING VILLAGE

# using key = [4, 1, -3, -2]
# translated = ROANOKE FILLER HEADING REST WITH SOUTH SNOW TRANSPORT ARE TO FREE YOU YOUR GONE SUPPLIES GODWIN IS TO JUST VILLAGE

# using key = [4, 1, -3, 2]
# translated = ROANOKE TO HEADING REST WITH GONE SNOW TRANSPORT ARE TO FREE YOU YOUR SOUTH SUPPLIES GODWIN IS FILLER JUST VILLAGE

# using key = [4, 1, 3, -2]
# translated = ROANOKE FILLER JUST REST WITH SOUTH SUPPLIES TRANSPORT ARE TO FREE YOU YOUR GONE SNOW GODWIN IS TO HEADING VILLAGE

# using key = [4, 1, 3, 2]
# translated = ROANOKE TO JUST REST WITH GONE SUPPLIES TRANSPORT ARE TO FREE YOU YOUR SOUTH SNOW GODWIN IS FILLER HEADING VILLAGE

# using key = [-4, -2, -1, -3]
# translated = HEADING IS FILLER VILLAGE SNOW YOUR SOUTH GODWIN FREE ARE TO YOU SUPPLIES WITH GONE TRANSPORT JUST ROANOKE TO REST

# using key = [-4, -2, -1, 3]
# translated = HEADING IS TO VILLAGE SNOW YOUR GONE GODWIN FREE ARE TO YOU SUPPLIES WITH SOUTH TRANSPORT JUST ROANOKE FILLER REST

# using key = [-4, -2, 1, -3]
# translated = JUST IS FILLER VILLAGE SUPPLIES YOUR SOUTH GODWIN FREE ARE TO YOU SNOW WITH GONE TRANSPORT HEADING ROANOKE TO REST

# using key = [-4, -2, 1, 3]
# translated = JUST IS TO VILLAGE SUPPLIES YOUR GONE GODWIN FREE ARE TO YOU SNOW WITH SOUTH TRANSPORT HEADING ROANOKE FILLER REST

# using key = [-4, 2, -1, -3]
# translated = HEADING ROANOKE FILLER VILLAGE SNOW WITH SOUTH GODWIN FREE ARE TO YOU SUPPLIES YOUR GONE TRANSPORT JUST IS TO REST

# using key = [-4, 2, -1, 3]
# translated = HEADING ROANOKE TO VILLAGE SNOW WITH GONE GODWIN FREE ARE TO YOU SUPPLIES YOUR SOUTH TRANSPORT JUST IS FILLER REST

# using key = [-4, 2, 1, -3]
# translated = JUST ROANOKE FILLER VILLAGE SUPPLIES WITH SOUTH GODWIN FREE ARE TO YOU SNOW YOUR GONE TRANSPORT HEADING IS TO REST

# using key = [-4, 2, 1, 3]
# translated = JUST ROANOKE TO VILLAGE SUPPLIES WITH GONE GODWIN FREE ARE TO YOU SNOW YOUR SOUTH TRANSPORT HEADING IS FILLER REST

# using key = [4, -2, -1, -3]
# translated = HEADING IS FILLER REST SNOW YOUR SOUTH TRANSPORT FREE ARE TO YOU SUPPLIES WITH GONE GODWIN JUST ROANOKE TO VILLAGE

# using key = [4, -2, -1, 3]
# translated = HEADING IS TO REST SNOW YOUR GONE TRANSPORT FREE ARE TO YOU SUPPLIES WITH SOUTH GODWIN JUST ROANOKE FILLER VILLAGE

# using key = [4, -2, 1, -3]
# translated = JUST IS FILLER REST SUPPLIES YOUR SOUTH TRANSPORT FREE ARE TO YOU SNOW WITH GONE GODWIN HEADING ROANOKE TO VILLAGE

# using key = [4, -2, 1, 3]
# translated = JUST IS TO REST SUPPLIES YOUR GONE TRANSPORT FREE ARE TO YOU SNOW WITH SOUTH GODWIN HEADING ROANOKE FILLER VILLAGE

# using key = [4, 2, -1, -3]
# translated = HEADING ROANOKE FILLER REST SNOW WITH SOUTH TRANSPORT FREE ARE TO YOU SUPPLIES YOUR GONE GODWIN JUST IS TO VILLAGE

# using key = [4, 2, -1, 3]
# translated = HEADING ROANOKE TO REST SNOW WITH GONE TRANSPORT FREE ARE TO YOU SUPPLIES YOUR SOUTH GODWIN JUST IS FILLER VILLAGE

# using key = [4, 2, 1, -3]
# translated = JUST ROANOKE FILLER REST SUPPLIES WITH SOUTH TRANSPORT FREE ARE TO YOU SNOW YOUR GONE GODWIN HEADING IS TO VILLAGE

# using key = [4, 2, 1, 3]
# translated = JUST ROANOKE TO REST SUPPLIES WITH GONE TRANSPORT FREE ARE TO YOU SNOW YOUR SOUTH GODWIN HEADING IS FILLER VILLAGE

# using key = [-4, -2, -3, -1]
# translated = FILLER IS HEADING VILLAGE SOUTH YOUR SNOW GODWIN TO ARE FREE YOU GONE WITH SUPPLIES TRANSPORT TO ROANOKE JUST REST

# using key = [-4, -2, -3, 1]
# translated = TO IS HEADING VILLAGE GONE YOUR SNOW GODWIN TO ARE FREE YOU SOUTH WITH SUPPLIES TRANSPORT FILLER ROANOKE JUST REST

# using key = [-4, -2, 3, -1]
# translated = FILLER IS JUST VILLAGE SOUTH YOUR SUPPLIES GODWIN TO ARE FREE YOU GONE WITH SNOW TRANSPORT TO ROANOKE HEADING REST

# using key = [-4, -2, 3, 1]
# translated = TO IS JUST VILLAGE GONE YOUR SUPPLIES GODWIN TO ARE FREE YOU SOUTH WITH SNOW TRANSPORT FILLER ROANOKE HEADING REST

# using key = [-4, 2, -3, -1]
# translated = FILLER ROANOKE HEADING VILLAGE SOUTH WITH SNOW GODWIN TO ARE FREE YOU GONE YOUR SUPPLIES TRANSPORT TO IS JUST REST

# using key = [-4, 2, -3, 1]
# translated = TO ROANOKE HEADING VILLAGE GONE WITH SNOW GODWIN TO ARE FREE YOU SOUTH YOUR SUPPLIES TRANSPORT FILLER IS JUST REST

# using key = [-4, 2, 3, -1]
# translated = FILLER ROANOKE JUST VILLAGE SOUTH WITH SUPPLIES GODWIN TO ARE FREE YOU GONE YOUR SNOW TRANSPORT TO IS HEADING REST

# using key = [-4, 2, 3, 1]
# translated = TO ROANOKE JUST VILLAGE GONE WITH SUPPLIES GODWIN TO ARE FREE YOU SOUTH YOUR SNOW TRANSPORT FILLER IS HEADING REST

# using key = [4, -2, -3, -1]
# translated = FILLER IS HEADING REST SOUTH YOUR SNOW TRANSPORT TO ARE FREE YOU GONE WITH SUPPLIES GODWIN TO ROANOKE JUST VILLAGE

# using key = [4, -2, -3, 1]
# translated = TO IS HEADING REST GONE YOUR SNOW TRANSPORT TO ARE FREE YOU SOUTH WITH SUPPLIES GODWIN FILLER ROANOKE JUST VILLAGE

# using key = [4, -2, 3, -1]
# translated = FILLER IS JUST REST SOUTH YOUR SUPPLIES TRANSPORT TO ARE FREE YOU GONE WITH SNOW GODWIN TO ROANOKE HEADING VILLAGE

# using key = [4, -2, 3, 1]
# translated = TO IS JUST REST GONE YOUR SUPPLIES TRANSPORT TO ARE FREE YOU SOUTH WITH SNOW GODWIN FILLER ROANOKE HEADING VILLAGE

# using key = [4, 2, -3, -1]
# translated = FILLER ROANOKE HEADING REST SOUTH WITH SNOW TRANSPORT TO ARE FREE YOU GONE YOUR SUPPLIES GODWIN TO IS JUST VILLAGE

# using key = [4, 2, -3, 1]
# translated = TO ROANOKE HEADING REST GONE WITH SNOW TRANSPORT TO ARE FREE YOU SOUTH YOUR SUPPLIES GODWIN FILLER IS JUST VILLAGE

# using key = [4, 2, 3, -1]
# translated = FILLER ROANOKE JUST REST SOUTH WITH SUPPLIES TRANSPORT TO ARE FREE YOU GONE YOUR SNOW GODWIN TO IS HEADING VILLAGE

# using key = [4, 2, 3, 1]
# translated = TO ROANOKE JUST REST GONE WITH SUPPLIES TRANSPORT TO ARE FREE YOU SOUTH YOUR SNOW GODWIN FILLER IS HEADING VILLAGE

# using key = [-4, -3, -1, -2]
# translated = HEADING FILLER IS VILLAGE SNOW SOUTH YOUR GODWIN FREE TO ARE YOU SUPPLIES GONE WITH TRANSPORT JUST TO ROANOKE REST

# using key = [-4, -3, -1, 2]
# translated = HEADING TO IS VILLAGE SNOW GONE YOUR GODWIN FREE TO ARE YOU SUPPLIES SOUTH WITH TRANSPORT JUST FILLER ROANOKE REST

# using key = [-4, -3, 1, -2]
# translated = JUST FILLER IS VILLAGE SUPPLIES SOUTH YOUR GODWIN FREE TO ARE YOU SNOW GONE WITH TRANSPORT HEADING TO ROANOKE REST

# using key = [-4, -3, 1, 2]
# translated = JUST TO IS VILLAGE SUPPLIES GONE YOUR GODWIN FREE TO ARE YOU SNOW SOUTH WITH TRANSPORT HEADING FILLER ROANOKE REST

# using key = [-4, 3, -1, -2]
# translated = HEADING FILLER ROANOKE VILLAGE SNOW SOUTH WITH GODWIN FREE TO ARE YOU SUPPLIES GONE YOUR TRANSPORT JUST TO IS REST

# using key = [-4, 3, -1, 2]
# translated = HEADING TO ROANOKE VILLAGE SNOW GONE WITH GODWIN FREE TO ARE YOU SUPPLIES SOUTH YOUR TRANSPORT JUST FILLER IS REST

# using key = [-4, 3, 1, -2]
# translated = JUST FILLER ROANOKE VILLAGE SUPPLIES SOUTH WITH GODWIN FREE TO ARE YOU SNOW GONE YOUR TRANSPORT HEADING TO IS REST

# using key = [-4, 3, 1, 2]
# translated = JUST TO ROANOKE VILLAGE SUPPLIES GONE WITH GODWIN FREE TO ARE YOU SNOW SOUTH YOUR TRANSPORT HEADING FILLER IS REST

# using key = [4, -3, -1, -2]
# translated = HEADING FILLER IS REST SNOW SOUTH YOUR TRANSPORT FREE TO ARE YOU SUPPLIES GONE WITH GODWIN JUST TO ROANOKE VILLAGE

# using key = [4, -3, -1, 2]
# translated = HEADING TO IS REST SNOW GONE YOUR TRANSPORT FREE TO ARE YOU SUPPLIES SOUTH WITH GODWIN JUST FILLER ROANOKE VILLAGE

# using key = [4, -3, 1, -2]
# translated = JUST FILLER IS REST SUPPLIES SOUTH YOUR TRANSPORT FREE TO ARE YOU SNOW GONE WITH GODWIN HEADING TO ROANOKE VILLAGE

# using key = [4, -3, 1, 2]
# translated = JUST TO IS REST SUPPLIES GONE YOUR TRANSPORT FREE TO ARE YOU SNOW SOUTH WITH GODWIN HEADING FILLER ROANOKE VILLAGE

# using key = [4, 3, -1, -2]
# translated = HEADING FILLER ROANOKE REST SNOW SOUTH WITH TRANSPORT FREE TO ARE YOU SUPPLIES GONE YOUR GODWIN JUST TO IS VILLAGE

# using key = [4, 3, -1, 2]
# translated = HEADING TO ROANOKE REST SNOW GONE WITH TRANSPORT FREE TO ARE YOU SUPPLIES SOUTH YOUR GODWIN JUST FILLER IS VILLAGE

# using key = [4, 3, 1, -2]
# translated = JUST FILLER ROANOKE REST SUPPLIES SOUTH WITH TRANSPORT FREE TO ARE YOU SNOW GONE YOUR GODWIN HEADING TO IS VILLAGE

# using key = [4, 3, 1, 2]
# translated = JUST TO ROANOKE REST SUPPLIES GONE WITH TRANSPORT FREE TO ARE YOU SNOW SOUTH YOUR GODWIN HEADING FILLER IS VILLAGE

# using key = [-4, -3, -2, -1]
# translated = FILLER HEADING IS VILLAGE SOUTH SNOW YOUR GODWIN TO FREE ARE YOU GONE SUPPLIES WITH TRANSPORT TO JUST ROANOKE REST

# using key = [-4, -3, -2, 1]
# translated = TO HEADING IS VILLAGE GONE SNOW YOUR GODWIN TO FREE ARE YOU SOUTH SUPPLIES WITH TRANSPORT FILLER JUST ROANOKE REST

# using key = [-4, -3, 2, -1]
# translated = FILLER JUST IS VILLAGE SOUTH SUPPLIES YOUR GODWIN TO FREE ARE YOU GONE SNOW WITH TRANSPORT TO HEADING ROANOKE REST

# using key = [-4, -3, 2, 1]
# translated = TO JUST IS VILLAGE GONE SUPPLIES YOUR GODWIN TO FREE ARE YOU SOUTH SNOW WITH TRANSPORT FILLER HEADING ROANOKE REST

# using key = [-4, 3, -2, -1]
# translated = FILLER HEADING ROANOKE VILLAGE SOUTH SNOW WITH GODWIN TO FREE ARE YOU GONE SUPPLIES YOUR TRANSPORT TO JUST IS REST

# using key = [-4, 3, -2, 1]
# translated = TO HEADING ROANOKE VILLAGE GONE SNOW WITH GODWIN TO FREE ARE YOU SOUTH SUPPLIES YOUR TRANSPORT FILLER JUST IS REST

# using key = [-4, 3, 2, -1]
# translated = FILLER JUST ROANOKE VILLAGE SOUTH SUPPLIES WITH GODWIN TO FREE ARE YOU GONE SNOW YOUR TRANSPORT TO HEADING IS REST

# using key = [-4, 3, 2, 1]
# translated = TO JUST ROANOKE VILLAGE GONE SUPPLIES WITH GODWIN TO FREE ARE YOU SOUTH SNOW YOUR TRANSPORT FILLER HEADING IS REST

# using key = [4, -3, -2, -1]
# translated = FILLER HEADING IS REST SOUTH SNOW YOUR TRANSPORT TO FREE ARE YOU GONE SUPPLIES WITH GODWIN TO JUST ROANOKE VILLAGE

# using key = [4, -3, -2, 1]
# translated = TO HEADING IS REST GONE SNOW YOUR TRANSPORT TO FREE ARE YOU SOUTH SUPPLIES WITH GODWIN FILLER JUST ROANOKE VILLAGE

# using key = [4, -3, 2, -1]
# translated = FILLER JUST IS REST SOUTH SUPPLIES YOUR TRANSPORT TO FREE ARE YOU GONE SNOW WITH GODWIN TO HEADING ROANOKE VILLAGE

# using key = [4, -3, 2, 1]
# translated = TO JUST IS REST GONE SUPPLIES YOUR TRANSPORT TO FREE ARE YOU SOUTH SNOW WITH GODWIN FILLER HEADING ROANOKE VILLAGE

# using key = [4, 3, -2, -1]
# translated = FILLER HEADING ROANOKE REST SOUTH SNOW WITH TRANSPORT TO FREE ARE YOU GONE SUPPLIES YOUR GODWIN TO JUST IS VILLAGE

# using key = [4, 3, -2, 1]
# translated = TO HEADING ROANOKE REST GONE SNOW WITH TRANSPORT TO FREE ARE YOU SOUTH SUPPLIES YOUR GODWIN FILLER JUST IS VILLAGE

# using key = [4, 3, 2, -1]
# translated = FILLER JUST ROANOKE REST SOUTH SUPPLIES WITH TRANSPORT TO FREE ARE YOU GONE SNOW YOUR GODWIN TO HEADING IS VILLAGE

# using key = [4, 3, 2, 1]
# translated = TO JUST ROANOKE REST GONE SUPPLIES WITH TRANSPORT TO FREE ARE YOU SOUTH SNOW YOUR GODWIN FILLER HEADING IS VILLAGE

# number of keys = 384